// Health & Nutritions

export const products = [
    {
        "id": "FMCH9HZW6CG2UMZZ",
        "title": "Refollium Hair Vitamin with Biotin + Anti Hair Fall Sha...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/c/w/z/hair-vitamin-with-biotin-anti-hair-fall-shampoo-prevent-hair-original-imah9hzwaazhxecw.jpeg?q=70",
        "price": 203,
        "original_price": 799,
        "discount": "74% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "refollium",
            "hair",
            "vitamin",
            "with",
            "biotin",
            "+",
            "anti",
            "hair",
            "fall",
            "sha..."
        ],
        "rating": "4.5",
        "stock_count": 46,
        "in_stock": true,
        "created_at": "2025-08-09T15:14:58.159Z",
        "review_count": 35,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "refollium-hair-vitamin-with-biotin-anti-hair-fall-sha-0"
    },
    {
        "id": "FMCGT2TZHBFZYFQG",
        "title": "KESARCO W320 Premium Cashews & Raw Almonds Combo | 200 ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/p/x/v/w320-premium-cashews-raw-almonds-combo-200-gm-each-6-kesarco-original-imahks9hzwxcs6qz.jpeg?q=70",
        "price": 396,
        "original_price": 1448,
        "discount": "72% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "kesarco",
            "w320",
            "premium",
            "cashews",
            "&",
            "raw",
            "almonds",
            "combo",
            "|",
            "200",
            "..."
        ],
        "rating": "4.9",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-04-27T00:54:21.130Z",
        "review_count": 483,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "kesarco-w320-premium-cashews-raw-almonds-combo-200-1"
    },
    {
        "id": "FMCHDZTVZAGPCVXY",
        "title": "Nooky Premium Dark Chocolate Gift | 4-in-1 Treat for Co...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/j/h/r/premium-dark-chocolate-gift-4-in-1-treat-for-couples-special-original-imahdztvdpvtzhyg.jpeg?q=70",
        "price": 440,
        "original_price": 1198,
        "discount": "63% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nooky",
            "premium",
            "dark",
            "chocolate",
            "gift",
            "|",
            "4-in-1",
            "treat",
            "for",
            "co..."
        ],
        "rating": "4.4",
        "stock_count": 13,
        "in_stock": true,
        "created_at": "2026-01-09T13:25:35.502Z",
        "review_count": 165,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nooky-premium-dark-chocolate-gift-4-in-1-treat-for-co-2"
    },
    {
        "id": "RAKFGBFSMGKP3BGC",
        "title": "Midiron IZ19Choco15ThailiRakhi1MUMN-DTRakhi-04 Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/jy0frm80/rakhi-set/b/g/c/iz19choco15thailirakhi1mumn-dtrakhi-04-midiron-original-imafgc4sejsmjstb.jpeg?q=70",
        "price": 265,
        "original_price": 999,
        "discount": "73% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "midiron",
            "iz19choco15thailirakhi1mumn-dtrakhi-04",
            "combo"
        ],
        "rating": "4.0",
        "stock_count": 27,
        "in_stock": true,
        "created_at": "2025-10-05T14:25:28.311Z",
        "review_count": 382,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "midiron-iz19choco15thailirakhi1mumn-dtrakhi-04-combo-3"
    },
    {
        "id": "FMCGXTKZNPSNMEYS",
        "title": "Aachi Royal Semiya Payasam Mix | B1G1 Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/7/0/b/royal-semiya-payasam-mix-b1g1-12-aachi-original-imagydmjgdnqyzbh.jpeg?q=70",
        "price": 126,
        "original_price": 190,
        "discount": "33% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "aachi",
            "royal",
            "semiya",
            "payasam",
            "mix",
            "|",
            "b1g1",
            "combo"
        ],
        "rating": "3.7",
        "stock_count": 14,
        "in_stock": true,
        "created_at": "2026-01-06T09:13:48.010Z",
        "review_count": 61,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "aachi-royal-semiya-payasam-mix-b1g1-combo-4"
    },
    {
        "id": "FMCG24JXJ3HZMKC8",
        "title": "Rajdhani CHANA SATTU 500 GRAMS PACK OF 1 WITH 200 GRAMS...",
        "image": "https://rukminim2.flixcart.com/image/612/612/kngd0nk0/fmcg-combo/2/y/p/chana-sattu-500-grams-pack-of-1-with-200-grams-of-sugar-r-a-j-d-original-imag24jwxhegxp7g.jpeg?q=70",
        "price": 101,
        "original_price": 379,
        "discount": "73% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "rajdhani",
            "chana",
            "sattu",
            "500",
            "grams",
            "pack",
            "of",
            "1",
            "with",
            "200",
            "grams..."
        ],
        "rating": "4.7",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-05-07T11:55:33.346Z",
        "review_count": 93,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "rajdhani-chana-sattu-500-grams-pack-of-1-with-200-grams-5"
    },
    {
        "id": "FMCGW5ZQYDNTXQVF",
        "title": "OddClick Unique Love You Forever gift Chocolate Gifts B...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/2/w/h/unique-love-you-forever-gift-chocolate-gifts-box-combo-pack-12-original-imah9kg9gnxuqksp.jpeg?q=70",
        "price": 268,
        "original_price": 699,
        "discount": "61% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "oddclick",
            "unique",
            "love",
            "you",
            "forever",
            "gift",
            "chocolate",
            "gifts",
            "b..."
        ],
        "rating": "3.1",
        "stock_count": 3,
        "in_stock": true,
        "created_at": "2025-11-17T19:40:06.640Z",
        "review_count": 390,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "oddclick-unique-love-you-forever-gift-chocolate-gifts-b-6"
    },
    {
        "id": "FMCGFUG8VGXGHU68",
        "title": "Herbalife Nutrition AFRESH TULSI+ELACHI Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/kn3i1zk0/fmcg-combo/y/s/3/afresh-tulsi-elachi-herbalife-nutrition-original-imagfug8vmrzzdk3.jpeg?q=70",
        "price": 1147,
        "original_price": 1780,
        "discount": "35% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "herbalife",
            "nutrition",
            "afresh",
            "tulsi+elachi",
            "combo"
        ],
        "rating": "3.7",
        "stock_count": 83,
        "in_stock": true,
        "created_at": "2026-02-22T03:42:19.514Z",
        "review_count": 429,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "herbalife-nutrition-afresh-tulsi-elachi-combo-7"
    },
    {
        "id": "FMCHFGJDHMBPEGHA",
        "title": "KESARCO Jeera and Saunf combo - 200 gm each | Cumin and...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/y/t/d/jeera-and-saunf-combo-200-gm-each-cumin-and-fennel-seeds-12-original-imahgvz9ehcedmaz.jpeg?q=70",
        "price": 127,
        "original_price": 640,
        "discount": "80% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "kesarco",
            "jeera",
            "and",
            "saunf",
            "combo",
            "-",
            "200",
            "gm",
            "each",
            "|",
            "cumin",
            "and..."
        ],
        "rating": "4.2",
        "stock_count": 76,
        "in_stock": true,
        "created_at": "2025-08-26T23:25:50.824Z",
        "review_count": 308,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "kesarco-jeera-and-saunf-combo-200-gm-each-cumin-and-8"
    },
    {
        "id": "FMCH92BAWRD7DDNS",
        "title": "Nut Urge Cashew+Raisins+Almond (200+200+200) Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/l/r/y/cashew-raisins-almond-200-200-200-8-nuturge-original-imah92baqcpzfwvt.jpeg?q=70",
        "price": 546,
        "original_price": 699,
        "discount": "21% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nut",
            "urge",
            "cashew+raisins+almond",
            "(200+200+200)",
            "combo"
        ],
        "rating": "4.0",
        "stock_count": 8,
        "in_stock": true,
        "created_at": "2025-08-22T04:28:09.271Z",
        "review_count": 96,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nut-urge-cashew-raisins-almond-200-200-200-combo-9"
    },
    {
        "id": "FMCHBHD3UF7AMY9F",
        "title": "Bevzilla 5 Ice Tea Powder Sachet (5 Flavours) & 24 Coff...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/m/m/j/5-ice-tea-powder-sachet-and-24-assorted-coffee-sachet-24-original-imahbhd3t9z4h9mw.jpeg?q=70",
        "price": 322,
        "original_price": 369,
        "discount": "12% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "bevzilla",
            "5",
            "ice",
            "tea",
            "powder",
            "sachet",
            "(5",
            "flavours)",
            "&",
            "24",
            "coff..."
        ],
        "rating": "4.0",
        "stock_count": 56,
        "in_stock": true,
        "created_at": "2025-06-08T14:40:08.007Z",
        "review_count": 270,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "bevzilla-5-ice-tea-powder-sachet-5-flavours-24-coff-10"
    },
    {
        "id": "FMCHF23YABQDGZJZ",
        "title": "Pro-To-Grow Combo of FitBhim Chocobanana Pancake Mix 25...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/s/d/9/combo-of-fitbhim-chocobanana-pancake-mix-250g-hazelnut-spread-original-imahkamcmgrwxreh.jpeg?q=70",
        "price": 690,
        "original_price": 768,
        "discount": "10% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "pro-to-grow",
            "combo",
            "of",
            "fitbhim",
            "chocobanana",
            "pancake",
            "mix",
            "25..."
        ],
        "rating": "4.1",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-04-14T00:32:44.231Z",
        "review_count": 379,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "pro-to-grow-combo-of-fitbhim-chocobanana-pancake-mix-25-11"
    },
    {
        "id": "FMCGZCQ6XZVZNYWH",
        "title": "ALPINO Natural Peanut Butter 1kg/Muesli Nut Delight 400...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/p/9/z/natural-peanut-butter-1kg-muesli-nut-delight-400gm-chocolate-original-imahhv952yndjvhx.jpeg?q=70",
        "price": 827,
        "original_price": 1257,
        "discount": "34% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "alpino",
            "natural",
            "peanut",
            "butter",
            "1kg/muesli",
            "nut",
            "delight",
            "400..."
        ],
        "rating": "4.4",
        "stock_count": 58,
        "in_stock": true,
        "created_at": "2026-01-20T12:32:50.436Z",
        "review_count": 484,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "alpino-natural-peanut-butter-1kg-muesli-nut-delight-400-12"
    },
    {
        "id": "FMCG9WH4EZYZZQVF",
        "title": "Vokin Biotech Herbal Insulux For Endocrine Health & Dia...",
        "image": "https://rukminim2.flixcart.com/image/612/612/kxw5tow0/fmcg-combo/l/c/g/herbal-insulux-for-endocrine-health-diabetes-control-vijaysar-original-imaga8wpfzzzeths.jpeg?q=70",
        "price": 896,
        "original_price": 1499,
        "discount": "40% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "vokin",
            "biotech",
            "herbal",
            "insulux",
            "for",
            "endocrine",
            "health",
            "&",
            "dia..."
        ],
        "rating": "3.9",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-11-02T09:17:20.660Z",
        "review_count": 198,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "vokin-biotech-herbal-insulux-for-endocrine-health-dia-13"
    },
    {
        "id": "FMCHK22PWMK6P2U3",
        "title": "Pro-To-Grow Fitbhim Nutritional Combo for Kids & Adults...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/x/y/y/fitbhim-nutritional-combo-for-kids-adults-gluten-free-breakfast-original-imahh97juwfcbk5y.jpeg?q=70",
        "price": 690,
        "original_price": 768,
        "discount": "10% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "pro-to-grow",
            "fitbhim",
            "nutritional",
            "combo",
            "for",
            "kids",
            "&",
            "adults..."
        ],
        "rating": "4.8",
        "stock_count": 11,
        "in_stock": true,
        "created_at": "2025-09-15T21:46:06.660Z",
        "review_count": 351,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "pro-to-grow-fitbhim-nutritional-combo-for-kids-adults-14"
    },
    {
        "id": "FMCH987FNBVKR2UC",
        "title": "Nut Urge Almond Pista Cashew Nuts Green Raisins Safawi ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/e/o/u/almond-pista-cashew-nuts-green-raisins-safawi-dates-150-150-150-original-imah987f7httvxac.jpeg?q=70",
        "price": 686,
        "original_price": 1549,
        "discount": "55% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nut",
            "urge",
            "almond",
            "pista",
            "cashew",
            "nuts",
            "green",
            "raisins",
            "safawi",
            "..."
        ],
        "rating": "4.9",
        "stock_count": 1,
        "in_stock": true,
        "created_at": "2026-02-05T17:56:38.831Z",
        "review_count": 339,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nut-urge-almond-pista-cashew-nuts-green-raisins-safawi-15"
    },
    {
        "id": "FMCHGAZGQST35VFT",
        "title": "BEST CHOICE NUTRITION Moringa Powder 100 gm & ACV Morin...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/s/d/y/moringa-powder-100-gm-acv-moringa-effervescent-tablets-masala-original-imahgazgegxm7xsf.jpeg?q=70",
        "price": 118,
        "original_price": 599,
        "discount": "80% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "best",
            "choice",
            "nutrition",
            "moringa",
            "powder",
            "100",
            "gm",
            "&",
            "acv",
            "morin..."
        ],
        "rating": "4.1",
        "stock_count": 39,
        "in_stock": true,
        "created_at": "2026-03-30T10:50:34.449Z",
        "review_count": 81,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "best-choice-nutrition-moringa-powder-100-gm-acv-morin-16"
    },
    {
        "id": "FMCHF49YYVCPFBF6",
        "title": "Nooky Mood Uplifting Chocolate & Cranberry Energy Drink...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/chocolate/f/g/i/240-mood-uplifting-chocolate-40g-cranberry-mood-drink-200ml-gift-original-imahf3ufzrgfg3mz.jpeg?q=70",
        "price": 448,
        "original_price": 649,
        "discount": "30% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nooky",
            "mood",
            "uplifting",
            "chocolate",
            "&",
            "cranberry",
            "energy",
            "drink..."
        ],
        "rating": "4.5",
        "stock_count": 33,
        "in_stock": true,
        "created_at": "2025-04-15T04:03:01.411Z",
        "review_count": 254,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nooky-mood-uplifting-chocolate-cranberry-energy-drink-17"
    },
    {
        "id": "FMCH52YMUJH4GVKK",
        "title": "Nut Urge CASHEW SPECIAL WHOLE 200gm+ALMOND BOLD 200gm C...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/h/w/f/cashew-special-whole-200gm-almond-bold-200gm-8-nut-urge-original-imah9gfxavxr5szh.jpeg?q=70",
        "price": 433,
        "original_price": 740,
        "discount": "41% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nut",
            "urge",
            "cashew",
            "special",
            "whole",
            "200gm+almond",
            "bold",
            "200gm",
            "c..."
        ],
        "rating": "3.1",
        "stock_count": 96,
        "in_stock": true,
        "created_at": "2025-12-11T05:48:47.322Z",
        "review_count": 415,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nut-urge-cashew-special-whole-200gm-almond-bold-200gm-c-18"
    },
    {
        "id": "FMCGXAZQAATPGEPG",
        "title": "GREEN PIECE Eggless Mayonnaise(250gm) and Schezwan Dipp...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/p/7/g/eggless-mayonnaise-250gm-and-schezwan-dipping-chutney-250gm-pack-original-imahc22pb7vgjkds.jpeg?q=70",
        "price": 173,
        "original_price": 599,
        "discount": "71% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "green",
            "piece",
            "eggless",
            "mayonnaise(250gm)",
            "and",
            "schezwan",
            "dipp..."
        ],
        "rating": "3.6",
        "stock_count": 5,
        "in_stock": true,
        "created_at": "2025-11-30T03:03:50.295Z",
        "review_count": 339,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "green-piece-eggless-mayonnaise-250gm-and-schezwan-dipp-19"
    },
    {
        "id": "FMCHFVPVZ23HJVAZ",
        "title": "bilipatra Nirant Churna200g, B12Greenfood Powder 200g C...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/j/g/c/nirant-churna200g-b12greenfood-powder-200g-combo-natural-original-imahfvpvh5ghbxq2.jpeg?q=70",
        "price": 785,
        "original_price": 800,
        "discount": "1% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "bilipatra",
            "nirant",
            "churna200g,",
            "b12greenfood",
            "powder",
            "200g",
            "c..."
        ],
        "rating": "3.5",
        "stock_count": 1,
        "in_stock": true,
        "created_at": "2025-08-13T00:51:00.027Z",
        "review_count": 116,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "bilipatra-nirant-churna200g-b12greenfood-powder-200g-c-20"
    },
    {
        "id": "FMCGZHERFAGHXAN6",
        "title": "Bevzilla Combo of 2 - 48 Butterscotch Coffee Sachet and...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/w/d/1/combo-of-2-48-butterscotch-coffee-sachet-and-48-hazelnut-coffee-original-imagzs59yqrtj2ze.jpeg?q=70",
        "price": 349,
        "original_price": 532,
        "discount": "34% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "bevzilla",
            "combo",
            "of",
            "2",
            "-",
            "48",
            "butterscotch",
            "coffee",
            "sachet",
            "and..."
        ],
        "rating": "3.8",
        "stock_count": 83,
        "in_stock": true,
        "created_at": "2025-09-03T13:22:40.298Z",
        "review_count": 139,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "bevzilla-combo-of-2-48-butterscotch-coffee-sachet-and-21"
    },
    {
        "id": "FMCH96W9GZZBNVGC",
        "title": "Triphal Shakti Plus Combo - Organic and Pure Powder - F...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/v/s/j/shakti-plus-combo-organic-and-pure-powder-for-strength-stamina-original-imah9px4cahfygr2.jpeg?q=70",
        "price": 1179,
        "original_price": 1690,
        "discount": "30% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "triphal",
            "shakti",
            "plus",
            "combo",
            "-",
            "organic",
            "and",
            "pure",
            "powder",
            "-",
            "f..."
        ],
        "rating": "4.3",
        "stock_count": 34,
        "in_stock": true,
        "created_at": "2026-01-02T16:45:30.724Z",
        "review_count": 318,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "triphal-shakti-plus-combo-organic-and-pure-powder-f-22"
    },
    {
        "id": "FMCGNJU9G9GNKGGH",
        "title": "Gustora Penne Pasta and Arrabbiata Sauce Combo Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/x/8/e/penne-pasta-and-arrabbiata-sauce-combo-12-gustora-original-imah8g2jhgphvqkt.jpeg?q=70",
        "price": 235,
        "original_price": 446,
        "discount": "47% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "gustora",
            "penne",
            "pasta",
            "and",
            "arrabbiata",
            "sauce",
            "combo",
            "combo"
        ],
        "rating": "3.9",
        "stock_count": 81,
        "in_stock": true,
        "created_at": "2026-01-19T06:06:31.258Z",
        "review_count": 225,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "gustora-penne-pasta-and-arrabbiata-sauce-combo-combo-23"
    },
    {
        "id": "FMCFXQZV9QXKUW8U",
        "title": "HERBALIFE Afresh Energy Drink Mix - Elaichi Flavor Comb...",
        "image": "https://rukminim2.flixcart.com/image/612/612/khtghow0-0/fmcg-combo/3/d/d/afresh-energy-drink-mix-elaichi-flavor-combo-pack-of-2-herbalife-original-imafxqzcfjmgegvv.jpeg?q=70",
        "price": 953,
        "original_price": 1826,
        "discount": "47% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "herbalife",
            "afresh",
            "energy",
            "drink",
            "mix",
            "-",
            "elaichi",
            "flavor",
            "comb..."
        ],
        "rating": "3.8",
        "stock_count": 85,
        "in_stock": true,
        "created_at": "2025-05-25T15:36:00.112Z",
        "review_count": 188,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "herbalife-afresh-energy-drink-mix-elaichi-flavor-comb-24"
    },
    {
        "id": "FMCGG54K3ZQ2MDSM",
        "title": "DHAMPUR GREEN Fruitales Mocktail Syrup Combo, Pack of 3...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/9/c/p/fruitales-mocktail-syrup-combo-pack-of-3-mocktail-mix-slushes-original-imah2hgmtvzamzje.jpeg?q=70",
        "price": 271,
        "original_price": 405,
        "discount": "33% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "dhampur",
            "green",
            "fruitales",
            "mocktail",
            "syrup",
            "combo,",
            "pack",
            "of",
            "3..."
        ],
        "rating": "4.8",
        "stock_count": 99,
        "in_stock": true,
        "created_at": "2025-08-06T10:58:31.301Z",
        "review_count": 122,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "dhampur-green-fruitales-mocktail-syrup-combo-pack-of-3-25"
    },
    {
        "id": "FMCG6ZDN6TPZ5GN3",
        "title": "Herbalife Nutrition Weight Loss & Management Combo With...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/n/p/u/weight-loss-management-combo-with-formula-1-nutritional-shake-original-imah5wvhgn6br8mx.jpeg?q=70",
        "price": 2572,
        "original_price": 4876,
        "discount": "47% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "herbalife",
            "nutrition",
            "weight",
            "loss",
            "&",
            "management",
            "combo",
            "with..."
        ],
        "rating": "3.3",
        "stock_count": 57,
        "in_stock": true,
        "created_at": "2026-03-28T13:12:16.324Z",
        "review_count": 232,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "herbalife-nutrition-weight-loss-management-combo-with-26"
    },
    {
        "id": "FMCGZHKC2F6M28GG",
        "title": "Bevzilla Pack of 96 Coffee Powder Sachet|Hot & Cold Ins...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/w/x/a/pack-of-96-coffee-sachet-hazelnut-and-vanilla-48-each-100-pure-original-imagzs5chpeqcd97.jpeg?q=70",
        "price": 359,
        "original_price": 598,
        "discount": "39% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "bevzilla",
            "pack",
            "of",
            "96",
            "coffee",
            "powder",
            "sachet|hot",
            "&",
            "cold",
            "ins..."
        ],
        "rating": "3.4",
        "stock_count": 16,
        "in_stock": true,
        "created_at": "2026-01-22T17:52:03.924Z",
        "review_count": 334,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "bevzilla-pack-of-96-coffee-powder-sachet-hot-cold-ins-27"
    },
    {
        "id": "FMCGYWTFQHQQ6KNE",
        "title": "KESARCO Jeera and Ajwain seeds combo | 200 gm each |Fla...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/l/o/y/jeera-and-ajwain-seeds-combo-200-gm-each-flavourful-and-original-imahgvpjgmgqvqtn.jpeg?q=70",
        "price": 166,
        "original_price": 720,
        "discount": "76% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "kesarco",
            "jeera",
            "and",
            "ajwain",
            "seeds",
            "combo",
            "|",
            "200",
            "gm",
            "each",
            "|fla..."
        ],
        "rating": "3.4",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-06-04T12:05:08.150Z",
        "review_count": 31,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "kesarco-jeera-and-ajwain-seeds-combo-200-gm-each-fla-28"
    },
    {
        "id": "FMCHC7F6MUPPHRYC",
        "title": "Baidyanath Ayurvedant ISABGOL 100g - Pack of 2 Combo",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/ayurvedic/t/m/x/ayurvedant-isabgol-100g-pack-of-2-2-baidyanath-original-imahc6ghdbugvkjm.jpeg?q=70",
        "price": 315,
        "original_price": 390,
        "discount": "19% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "baidyanath",
            "ayurvedant",
            "isabgol",
            "100g",
            "-",
            "pack",
            "of",
            "2",
            "combo"
        ],
        "rating": "3.2",
        "stock_count": 58,
        "in_stock": true,
        "created_at": "2025-11-29T21:05:00.178Z",
        "review_count": 92,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "baidyanath-ayurvedant-isabgol-100g-pack-of-2-combo-29"
    },
    {
        "id": "FMCHJH7HXWZSXHVP",
        "title": "NUTS & ROOTS Okra Chips Combo | Real Vegetable | Vacuum...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/fmcg-combo/7/e/c/okra-chips-combo-real-vegetable-vacuum-fried-healthy-snack-12-original-imahjh7hn4tzk6xh.jpeg?q=70",
        "price": 258,
        "original_price": 440,
        "discount": "41% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nuts",
            "&",
            "roots",
            "okra",
            "chips",
            "combo",
            "|",
            "real",
            "vegetable",
            "|",
            "vacuum..."
        ],
        "rating": "3.7",
        "stock_count": 19,
        "in_stock": true,
        "created_at": "2025-11-22T21:57:30.074Z",
        "review_count": 314,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nuts-roots-okra-chips-combo-real-vegetable-vacuum-30"
    },
    {
        "id": "FMCGJNXHAAPNZGTJ",
        "title": "HERBALIFE Formula 1 Kulfi500g+Proteinpowder200g+AfreshG...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/protein-supplement/x/b/l/plant-based-protein-nutrition-formula-1-kulfi500g-protein-powder-original-imagjg4xuv8vaabh.jpeg?q=70",
        "price": 2221,
        "original_price": 4676,
        "discount": "52% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "herbalife",
            "formula",
            "1",
            "kulfi500g+proteinpowder200g+afreshg..."
        ],
        "rating": "3.2",
        "stock_count": 23,
        "in_stock": true,
        "created_at": "2025-12-21T04:07:39.454Z",
        "review_count": 252,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "herbalife-formula-1-kulfi500g-proteinpowder200g-afreshg-31"
    },
    {
        "id": "VSLGSJMSBE2WAXE6",
        "title": "Miduty Liver Detox - Milk Thistle with NAC 900mg for Fa...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/r/w/k/60-liver-detox-milk-thistle-with-nac-900mg-for-fatty-liver-original-imahkz76ywexffgf.jpeg?q=70",
        "price": 1400,
        "original_price": null,
        "discount": null,
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "miduty",
            "liver",
            "detox",
            "-",
            "milk",
            "thistle",
            "with",
            "nac",
            "900mg",
            "for",
            "fa..."
        ],
        "rating": "4.8",
        "stock_count": 95,
        "in_stock": true,
        "created_at": "2025-06-07T15:19:09.422Z",
        "review_count": 33,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "miduty-liver-detox-milk-thistle-with-nac-900mg-for-fa-32"
    },
    {
        "id": "VSLHDAF3TRNG7BB9",
        "title": "Miduty Pigment+ Skin Shield Anti-Aging & Skin Hydration...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/8/2/e/60-pigment-skin-shield-anti-aging-skin-hydration-supplement-with-original-imahghkmtzknghst.jpeg?q=70",
        "price": 2428,
        "original_price": null,
        "discount": null,
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "miduty",
            "pigment+",
            "skin",
            "shield",
            "anti-aging",
            "&",
            "skin",
            "hydration..."
        ],
        "rating": "3.7",
        "stock_count": 52,
        "in_stock": true,
        "created_at": "2025-10-25T01:38:47.822Z",
        "review_count": 265,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "miduty-pigment-skin-shield-anti-aging-skin-hydration-33"
    },
    {
        "id": "VSLGHETGX6HKJQFF",
        "title": "Centrum Men|Supports Overall Health (Veg) | World's No....",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/r/q/o/-original-imahhb6zg65tf7fw.jpeg?q=70",
        "price": 312,
        "original_price": 440,
        "discount": "29% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "centrum",
            "men|supports",
            "overall",
            "health",
            "(veg)",
            "|",
            "world's",
            "no...."
        ],
        "rating": "4.7",
        "stock_count": 5,
        "in_stock": true,
        "created_at": "2026-03-28T20:49:09.632Z",
        "review_count": 97,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "centrum-men-supports-overall-health-veg-world-s-no-34"
    },
    {
        "id": "VSLHEHUUJNYACNHH",
        "title": "Srishma Ayurvedic Gainer+ Weight Gain Supplement Helps ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/q/q/i/90-ayurvedic-gainer-weight-gain-supplement-helps-in-gaining-original-imahkkgscqnkcf3s.jpeg?q=70",
        "price": 362,
        "original_price": 1099,
        "discount": "67% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "srishma",
            "ayurvedic",
            "gainer+",
            "weight",
            "gain",
            "supplement",
            "helps",
            "..."
        ],
        "rating": "3.3",
        "stock_count": 54,
        "in_stock": true,
        "created_at": "2025-07-02T04:21:51.994Z",
        "review_count": 225,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "srishma-ayurvedic-gainer-weight-gain-supplement-helps-35"
    },
    {
        "id": "VSLGGTYDBRZN8BHZ",
        "title": "GNC Calcium Plus With Magnesium & Vitamin D3",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/b/o/h/-original-imahceb5zkrtrzqj.jpeg?q=70",
        "price": 351,
        "original_price": 449,
        "discount": "21% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "gnc",
            "calcium",
            "plus",
            "with",
            "magnesium",
            "&",
            "vitamin",
            "d3"
        ],
        "rating": "4.1",
        "stock_count": 26,
        "in_stock": true,
        "created_at": "2026-01-23T09:53:36.815Z",
        "review_count": 243,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "gnc-calcium-plus-with-magnesium-vitamin-d3-36"
    },
    {
        "id": "VSLGFBS6DKFGX8FN",
        "title": "Purna Gummies Superfruits Collagen Mixed Fruit Flavor G...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/l/4/w/30-superfruits-collagen-mixed-fruit-flavor-gummies-for-hair-and-original-imagugy57jed7tza.jpeg?q=70",
        "price": 149,
        "original_price": 549,
        "discount": "72% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "purna",
            "gummies",
            "superfruits",
            "collagen",
            "mixed",
            "fruit",
            "flavor",
            "g..."
        ],
        "rating": "5.0",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-08-23T00:11:57.012Z",
        "review_count": 234,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "purna-gummies-superfruits-collagen-mixed-fruit-flavor-g-37"
    },
    {
        "id": "VSLGHYDYTXUPGEZE",
        "title": "Good Monk Family Nutrition Mix|Energy & Immunity|Multiv...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/i/s/3/15-family-nutrition-mix-energy-immunity-multivitamin-b12-c-d-original-imahhy4njujzfmn7.jpeg?q=70",
        "price": 299,
        "original_price": 370,
        "discount": "19% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "good",
            "monk",
            "family",
            "nutrition",
            "mix|energy",
            "&",
            "immunity|multiv..."
        ],
        "rating": "4.0",
        "stock_count": 26,
        "in_stock": true,
        "created_at": "2026-01-28T12:45:56.919Z",
        "review_count": 142,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "good-monk-family-nutrition-mix-energy-immunity-multiv-38"
    },
    {
        "id": "VSLGSKPFYGNTS7MH",
        "title": "Miduty Multivitamin One Per Day-Multimineral supplement...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/u/9/i/30-multivitamin-one-per-day-multimineral-supplement-omega-3-original-imahgcjgyakcqgz5.jpeg?q=70",
        "price": 746,
        "original_price": null,
        "discount": null,
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "miduty",
            "multivitamin",
            "one",
            "per",
            "day-multimineral",
            "supplement..."
        ],
        "rating": "4.4",
        "stock_count": 33,
        "in_stock": true,
        "created_at": "2025-12-03T03:18:41.545Z",
        "review_count": 32,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "miduty-multivitamin-one-per-day-multimineral-supplement-39"
    },
    {
        "id": "VSLGHUKSWWHV25CY",
        "title": "VITASTA Body Grow capsule for Fast Weight and Muscle ga...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/g/h/f/50-body-grow-capsule-for-fast-weight-and-muscle-gain-100-natural-original-imaghuksqv5qzvef.jpeg?q=70",
        "price": 180,
        "original_price": 899,
        "discount": "79% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "vitasta",
            "body",
            "grow",
            "capsule",
            "for",
            "fast",
            "weight",
            "and",
            "muscle",
            "ga..."
        ],
        "rating": "4.9",
        "stock_count": 59,
        "in_stock": true,
        "created_at": "2026-03-19T06:39:52.687Z",
        "review_count": 130,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "vitasta-body-grow-capsule-for-fast-weight-and-muscle-ga-40"
    },
    {
        "id": "VSLFYTP9MDGJRFDZ",
        "title": "MUSCLEBLAZE Liquid L-Carnitine 1100 mg, Helps Convert F...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/f/q/y/450-liquid-l-carnitine-1100-mg-helps-convert-fat-into-energy-fat-original-imahkxx9ebgngbzh.jpeg?q=70",
        "price": 699,
        "original_price": 799,
        "discount": "12% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "muscleblaze",
            "liquid",
            "l-carnitine",
            "1100",
            "mg,",
            "helps",
            "convert",
            "f..."
        ],
        "rating": "4.9",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-05-24T22:05:35.524Z",
        "review_count": 143,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "muscleblaze-liquid-l-carnitine-1100-mg-helps-convert-f-41"
    },
    {
        "id": "PSLGTNNYZ5UE8MHB",
        "title": "Lakshmi Krishna Slim & Strength Powder for Weight Loss ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/protein-supplement/m/h/v/protein-blends-slim-strength-powder-for-weight-loss-4421-lakshmi-original-imahjn76jhggzr8n.jpeg?q=70",
        "price": 900,
        "original_price": 1200,
        "discount": "25% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "lakshmi",
            "krishna",
            "slim",
            "&",
            "strength",
            "powder",
            "for",
            "weight",
            "loss",
            "..."
        ],
        "rating": "4.6",
        "stock_count": 56,
        "in_stock": true,
        "created_at": "2025-08-24T04:17:20.136Z",
        "review_count": 480,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "lakshmi-krishna-slim-strength-powder-for-weight-loss-42"
    },
    {
        "id": "VSLFMUSJMZ2AFGPZ",
        "title": "AS-IT-IS Nutrition Nutrition Tribulus 500mg per serving...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/h/y/y/60-nutrition-tribulus-500mg-per-serving-90-capsules-special-original-imahkffhquxegttw.jpeg?q=70",
        "price": 382,
        "original_price": 557,
        "discount": "31% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "as-it-is",
            "nutrition",
            "nutrition",
            "tribulus",
            "500mg",
            "per",
            "serving..."
        ],
        "rating": "3.1",
        "stock_count": 62,
        "in_stock": true,
        "created_at": "2026-04-05T18:53:34.388Z",
        "review_count": 99,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "as-it-is-nutrition-nutrition-tribulus-500mg-per-serving-43"
    },
    {
        "id": "VSLGGUHFQPFUNG6S",
        "title": "NutraChoice Fish Oil Double Strength Omega-3 (360mg EPA...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/5/m/a/60-fish-oil-double-strength-omega-3-360mg-epa-240mg-dha-for-original-imahgewye85fvzuq.jpeg?q=70",
        "price": 250,
        "original_price": 999,
        "discount": "74% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nutrachoice",
            "fish",
            "oil",
            "double",
            "strength",
            "omega-3",
            "(360mg",
            "epa..."
        ],
        "rating": "3.2",
        "stock_count": 0,
        "in_stock": false,
        "created_at": "2025-09-16T02:15:20.744Z",
        "review_count": 418,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nutrachoice-fish-oil-double-strength-omega-3-360mg-epa-44"
    },
    {
        "id": "VSLGFB3MBPXV5MTK",
        "title": "MUSCLEBLAZE Biozyme Daily Multivitamin for Men, 5-in-1 ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/g/t/t/90-biozyme-daily-multivitamin-for-men-5-in-1-supplement-multi-original-imahkxx8xrt2bfez.jpeg?q=70",
        "price": 899,
        "original_price": 1159,
        "discount": "22% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "muscleblaze",
            "biozyme",
            "daily",
            "multivitamin",
            "for",
            "men,",
            "5-in-1",
            "..."
        ],
        "rating": "4.2",
        "stock_count": 35,
        "in_stock": true,
        "created_at": "2025-12-26T22:40:52.720Z",
        "review_count": 285,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "muscleblaze-biozyme-daily-multivitamin-for-men-5-in-1-45"
    },
    {
        "id": "PSLECHPA2JGHHSFU",
        "title": "Protinex Original Nutrition Drink Powder with Protein f...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/milk-drink-mix/d/0/4/-original-imahhbsxrjevwy2u.jpeg?q=70",
        "price": 638,
        "original_price": 665,
        "discount": "4% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "protinex",
            "original",
            "nutrition",
            "drink",
            "powder",
            "with",
            "protein",
            "f..."
        ],
        "rating": "3.2",
        "stock_count": 39,
        "in_stock": true,
        "created_at": "2026-03-21T12:22:57.100Z",
        "review_count": 177,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "protinex-original-nutrition-drink-powder-with-protein-f-46"
    },
    {
        "id": "VSLGYSXKWNUDEJGZ",
        "title": "HEALTHKART HK Vitals Multivitamin with Probiotics, Immu...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/d/6/z/60-hk-vitals-multivitamin-with-probiotics-immunity-and-gut-original-imahhu47q7ba98px.jpeg?q=70",
        "price": 375,
        "original_price": 419,
        "discount": "10% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "healthkart",
            "hk",
            "vitals",
            "multivitamin",
            "with",
            "probiotics,",
            "immu..."
        ],
        "rating": "4.8",
        "stock_count": 73,
        "in_stock": true,
        "created_at": "2025-11-21T22:38:41.599Z",
        "review_count": 405,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "healthkart-hk-vitals-multivitamin-with-probiotics-immu-47"
    },
    {
        "id": "VSLGRSYKJ2SGYPSR",
        "title": "VITASTA Body Grow Capsule For Fast Weight and Muscle Ga...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/ayurvedic/y/h/j/body-grow-ayurvedic-mass-gainer-muscle-gainer-weight-gainer-original-imagqtye47pwah6x.jpeg?q=70",
        "price": 162,
        "original_price": 999,
        "discount": "83% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "vitasta",
            "body",
            "grow",
            "capsule",
            "for",
            "fast",
            "weight",
            "and",
            "muscle",
            "ga..."
        ],
        "rating": "3.3",
        "stock_count": 100,
        "in_stock": true,
        "created_at": "2025-09-27T19:21:14.754Z",
        "review_count": 31,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "vitasta-body-grow-capsule-for-fast-weight-and-muscle-ga-48"
    },
    {
        "id": "VSLGHBGZ63HPTMYE",
        "title": "HEALTHKART HK Vitals Skin Radiance Collagen Supplement ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/l/i/k/100-hk-vitals-skin-radiance-collagen-supplement-with-biotin-original-imahhw7rj2thfvzf.jpeg?q=70",
        "price": 360,
        "original_price": 509,
        "discount": "29% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "healthkart",
            "hk",
            "vitals",
            "skin",
            "radiance",
            "collagen",
            "supplement",
            "..."
        ],
        "rating": "4.8",
        "stock_count": 69,
        "in_stock": true,
        "created_at": "2025-05-06T18:23:05.568Z",
        "review_count": 482,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "healthkart-hk-vitals-skin-radiance-collagen-supplement-49"
    },
    {
        "id": "VSLFNVADKABXTKDR",
        "title": "GNC Mega Men One Daily Multivitamin for Men",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/c/1/8/60-mega-men-one-daily-multivitamin-for-men-multi-vitamin-gnc-original-imahcyymjzxfrvp5.jpeg?q=70",
        "price": 609,
        "original_price": 1099,
        "discount": "44% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "gnc",
            "mega",
            "men",
            "one",
            "daily",
            "multivitamin",
            "for",
            "men"
        ],
        "rating": "3.3",
        "stock_count": 74,
        "in_stock": true,
        "created_at": "2026-01-27T07:08:21.951Z",
        "review_count": 353,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "gnc-mega-men-one-daily-multivitamin-for-men-50"
    },
    {
        "id": "VSLGHGWGC4YCWQH6",
        "title": "Centrum Adult 50+|Supports Overall Health|World's No.1 ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/p/o/l/-original-imagzhszr3gkevbq.jpeg?q=70",
        "price": 328,
        "original_price": 463,
        "discount": "29% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "centrum",
            "adult",
            "50+|supports",
            "overall",
            "health|world's",
            "no.1",
            "..."
        ],
        "rating": "4.7",
        "stock_count": 67,
        "in_stock": true,
        "created_at": "2026-01-15T07:02:44.815Z",
        "review_count": 473,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "centrum-adult-50-supports-overall-health-world-s-no-1-51"
    },
    {
        "id": "VSLG9G5ZXUBHGMFF",
        "title": "AS-IT-IS Nutrition ATOM Multivitamin for Men & Women - ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/9/w/r/60-atom-multivitamin-for-men-women-60-capsules-multi-vitamin-as-original-imahj4gqr3mbaf6n.jpeg?q=70",
        "price": 349,
        "original_price": 508,
        "discount": "31% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "as-it-is",
            "nutrition",
            "atom",
            "multivitamin",
            "for",
            "men",
            "&",
            "women",
            "-",
            "..."
        ],
        "rating": "3.6",
        "stock_count": 18,
        "in_stock": true,
        "created_at": "2025-08-05T09:47:38.052Z",
        "review_count": 442,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "as-it-is-nutrition-atom-multivitamin-for-men-women-52"
    },
    {
        "id": "VSLHHFK6UBHQKYPT",
        "title": "HEALTHPRIME LABS The Bodybuilder Mass Gainer/Weight Gai...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/l/g/m/60-0-the-bodybuilder-mass-gainer-weight-gainer-capsules-for-original-imahhfk6ptuqtxhz.jpeg?q=70",
        "price": 180,
        "original_price": 367,
        "discount": "50% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "healthprime",
            "labs",
            "the",
            "bodybuilder",
            "mass",
            "gainer/weight",
            "gai..."
        ],
        "rating": "4.0",
        "stock_count": 77,
        "in_stock": true,
        "created_at": "2026-02-05T07:19:32.597Z",
        "review_count": 39,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "healthprime-labs-the-bodybuilder-mass-gainer-weight-gai-53"
    },
    {
        "id": "VSLGZ4GYYDDTSKVF",
        "title": "Health Ok Multivitamin with Natural Ginseng and Taurine...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/r/6/w/60-multivitamin-with-natural-ginseng-and-taurine-power-100-original-imahdesdxvhuz4gh.jpeg?q=70",
        "price": 250,
        "original_price": 489,
        "discount": "48% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "health",
            "ok",
            "multivitamin",
            "with",
            "natural",
            "ginseng",
            "and",
            "taurine..."
        ],
        "rating": "3.1",
        "stock_count": 27,
        "in_stock": true,
        "created_at": "2025-08-10T21:06:28.389Z",
        "review_count": 73,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "health-ok-multivitamin-with-natural-ginseng-and-taurine-54"
    },
    {
        "id": "VSLFE7PDUC978FJR",
        "title": "MUSCLEBLAZE Strongher Women Multivitamin, Multivitamin ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/s/o/a/60-strongher-women-multivitamin-multivitamin-for-women-for-original-imahkxx9fs5zmagm.jpeg?q=70",
        "price": 549,
        "original_price": 799,
        "discount": "31% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "muscleblaze",
            "strongher",
            "women",
            "multivitamin,",
            "multivitamin",
            "..."
        ],
        "rating": "4.3",
        "stock_count": 100,
        "in_stock": true,
        "created_at": "2026-03-04T08:04:30.669Z",
        "review_count": 356,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "muscleblaze-strongher-women-multivitamin-multivitamin-55"
    },
    {
        "id": "VSLHYYWZ4TH4NAYK",
        "title": "Hairbless HEALTHSUPPLEMENT TABLETS",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/d/m/x/30-healthsupplement-tablets-special-supplements-hairbless-original-imahyywzr4pujhyf.jpeg?q=70",
        "price": 446,
        "original_price": 670,
        "discount": "33% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "hairbless",
            "healthsupplement",
            "tablets"
        ],
        "rating": "4.8",
        "stock_count": 92,
        "in_stock": true,
        "created_at": "2025-10-22T10:56:44.006Z",
        "review_count": 249,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "hairbless-healthsupplement-tablets-56"
    },
    {
        "id": "VSLGEJDW6JUGH7ZT",
        "title": "NUTRELA Daily Energy Capsules With Vitamin B-Complesand...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-vitamin-supplement/x/l/g/30-daily-energy-biofermented-b-complex-for-men-women-multi-original-imahcc4txpg7ehyr.jpeg?q=70",
        "price": 211,
        "original_price": 267,
        "discount": "20% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nutrela",
            "daily",
            "energy",
            "capsules",
            "with",
            "vitamin",
            "b-complesand..."
        ],
        "rating": "4.5",
        "stock_count": 92,
        "in_stock": true,
        "created_at": "2026-03-24T16:07:46.358Z",
        "review_count": 115,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nutrela-daily-energy-capsules-with-vitamin-b-complesand-57"
    },
    {
        "id": "VSLGBUNNZBZCGTDM",
        "title": "PATANJALI Daily Active Capsule 750mg - Pack of 1",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/shopsy-vitamin-supplement/m/y/1/30-daily-active-multivitamin-for-men-women-multi-vitamin-nutrela-original-imahcc4tssy8pfuf.jpeg?q=70",
        "price": 314,
        "original_price": 356,
        "discount": "11% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "patanjali",
            "daily",
            "active",
            "capsule",
            "750mg",
            "-",
            "pack",
            "of",
            "1"
        ],
        "rating": "3.2",
        "stock_count": 13,
        "in_stock": true,
        "created_at": "2026-02-20T01:11:36.277Z",
        "review_count": 124,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "patanjali-daily-active-capsule-750mg-pack-of-1-58"
    },
    {
        "id": "VSLHFDSDHYQUJKP8",
        "title": "Srishma W-Gainer+ Capsule Muscle Gainer I Promotes Musc...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/1/q/9/90-w-gainer-capsule-muscle-gainer-i-promotes-muscle-gain-original-imahfuugymwptabf.jpeg?q=70",
        "price": 315,
        "original_price": 1099,
        "discount": "71% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "srishma",
            "w-gainer+",
            "capsule",
            "muscle",
            "gainer",
            "i",
            "promotes",
            "musc..."
        ],
        "rating": "4.7",
        "stock_count": 3,
        "in_stock": true,
        "created_at": "2025-10-14T12:24:01.323Z",
        "review_count": 369,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "srishma-w-gainer-capsule-muscle-gainer-i-promotes-musc-59"
    },
    {
        "id": "VSLGKZHMGSQAGQCH",
        "title": "HEALTHKART HK Vitals Skin Radiance Collagen Supplement ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/f/a/e/200-hk-vitals-skin-radiance-collagen-supplement-with-biotin-original-imahhw7tvz4fpuzz.jpeg?q=70",
        "price": 849,
        "original_price": 909,
        "discount": "6% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "healthkart",
            "hk",
            "vitals",
            "skin",
            "radiance",
            "collagen",
            "supplement",
            "..."
        ],
        "rating": "3.0",
        "stock_count": 35,
        "in_stock": true,
        "created_at": "2025-09-13T21:40:41.663Z",
        "review_count": 31,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "healthkart-hk-vitals-skin-radiance-collagen-supplement-60"
    },
    {
        "id": "VSLH9EHXA2GFK3Z6",
        "title": "TATA 1mg Salmon Omega 3 Fish Oil| Advanced Fish Oil sup...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/i/x/a/120-salmon-omega-3-fish-oil-advanced-fish-oil-supplement-with-original-imahbjfgmtpqasxk.jpeg?q=70",
        "price": 662,
        "original_price": 992,
        "discount": "33% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "tata",
            "1mg",
            "salmon",
            "omega",
            "3",
            "fish",
            "oil|",
            "advanced",
            "fish",
            "oil",
            "sup..."
        ],
        "rating": "3.2",
        "stock_count": 34,
        "in_stock": true,
        "created_at": "2026-02-05T18:46:04.815Z",
        "review_count": 462,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "tata-1mg-salmon-omega-3-fish-oil-advanced-fish-oil-sup-61"
    },
    {
        "id": "VSLGZ2VBNW4ZMG5N",
        "title": "DNUTRIXN Advance Ashwagandha KSM-66 |Advanced Formulati...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/a/i/j/30-advance-ashwagandha-ksm-66-advanced-formulation-weight-gain-original-imagz3mdmgf4gfmf.jpeg?q=70",
        "price": 248,
        "original_price": 899,
        "discount": "72% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "dnutrixn",
            "advance",
            "ashwagandha",
            "ksm-66",
            "|advanced",
            "formulati..."
        ],
        "rating": "3.4",
        "stock_count": 9,
        "in_stock": true,
        "created_at": "2025-06-17T04:01:59.595Z",
        "review_count": 307,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "dnutrixn-advance-ashwagandha-ksm-66-advanced-formulati-62"
    },
    {
        "id": "VSLFPGG5FAMSN895",
        "title": "HEALTHKART HK Vitals Biotin, High Strength Supplement f...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/r/s/u/60-hk-vitals-biotin-high-strength-supplement-for-hair-growth-original-imahhu3u7vr4ny7h.jpeg?q=70",
        "price": 339,
        "original_price": 469,
        "discount": "27% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "healthkart",
            "hk",
            "vitals",
            "biotin,",
            "high",
            "strength",
            "supplement",
            "f..."
        ],
        "rating": "4.8",
        "stock_count": 94,
        "in_stock": true,
        "created_at": "2025-10-22T10:06:59.296Z",
        "review_count": 181,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "healthkart-hk-vitals-biotin-high-strength-supplement-f-63"
    },
    {
        "id": "VSLEXJZHFRWWWZNN",
        "title": "MUSCLEBLAZE MB-VITE Multivitamin",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/g/c/a/120-mb-vite-multivitamin-multi-vitamin-muscleblaze-original-imahkxx9npfuvsyd.jpeg?q=70",
        "price": 899,
        "original_price": 1299,
        "discount": "30% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "muscleblaze",
            "mb-vite",
            "multivitamin"
        ],
        "rating": "3.6",
        "stock_count": 21,
        "in_stock": true,
        "created_at": "2025-06-05T04:09:43.710Z",
        "review_count": 195,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "muscleblaze-mb-vite-multivitamin-64"
    },
    {
        "id": "VSLFGU6ZHZRQDH7B",
        "title": "OZiva 10000+ mcg (With Amla, Sesbania), Natural Biotin ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/a/g/f/125-10000-mcg-with-amla-sesbania-natural-biotin-for-hair-growth-original-imahy8ncfq3zzk7f.jpeg?q=70",
        "price": 466,
        "original_price": 649,
        "discount": "28% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "oziva",
            "10000+",
            "mcg",
            "(with",
            "amla,",
            "sesbania),",
            "natural",
            "biotin",
            "..."
        ],
        "rating": "4.6",
        "stock_count": 45,
        "in_stock": true,
        "created_at": "2025-07-31T22:21:15.258Z",
        "review_count": 250,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "oziva-10000-mcg-with-amla-sesbania-natural-biotin-65"
    },
    {
        "id": "VSLHJFZ7PAFCZKFM",
        "title": "PUREFUSION Multivitamin Capsules for Men & Women Daily ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/w/2/q/60-multivitamin-capsules-for-men-women-daily-nutrition-and-original-imahjfz7mbaf2bmr.jpeg?q=70",
        "price": 380,
        "original_price": 599,
        "discount": "36% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "purefusion",
            "multivitamin",
            "capsules",
            "for",
            "men",
            "&",
            "women",
            "daily",
            "..."
        ],
        "rating": "3.1",
        "stock_count": 54,
        "in_stock": true,
        "created_at": "2026-04-04T01:07:49.270Z",
        "review_count": 81,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "purefusion-multivitamin-capsules-for-men-women-daily-66"
    },
    {
        "id": "VSLHHFXWB5E6FM8T",
        "title": "MeTAboLix Lean Balance Berberine Plus Weight Loss & Hor...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/1/d/t/14-lean-balance-berberine-plus-weight-loss-hormone-support-4-in-original-imahhfxwvjcugcee.jpeg?q=70",
        "price": 500,
        "original_price": 699,
        "discount": "28% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "metabolix",
            "lean",
            "balance",
            "berberine",
            "plus",
            "weight",
            "loss",
            "&",
            "hor..."
        ],
        "rating": "3.0",
        "stock_count": 62,
        "in_stock": true,
        "created_at": "2026-01-01T03:09:28.422Z",
        "review_count": 379,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "metabolix-lean-balance-berberine-plus-weight-loss-hor-67"
    },
    {
        "id": "VSLFS6VFVASA6WVU",
        "title": "Cipla Maxirich MV & Mineral Softgels - 30 capsules",
        "image": "https://rukminim2.flixcart.com/image/612/612/kar44280/vitamin-supplement/w/v/u/30-maxirich-mv-mineral-softgels-30-capsules-cipla-original-imafs962shz8nzpr.jpeg?q=70",
        "price": 225,
        "original_price": 330,
        "discount": "31% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "cipla",
            "maxirich",
            "mv",
            "&",
            "mineral",
            "softgels",
            "-",
            "30",
            "capsules"
        ],
        "rating": "4.4",
        "stock_count": 6,
        "in_stock": true,
        "created_at": "2025-05-03T21:08:48.172Z",
        "review_count": 417,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "cipla-maxirich-mv-mineral-softgels-30-capsules-68"
    },
    {
        "id": "VSLHBRWGGS5C75WT",
        "title": "Vedapulse Quercetin 500mg Capsules – Allergy Relief & I...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/x/a/x/500-quercetin-500mg-capsules-allergy-relief-immune-health-original-imahcgzfznsqhywt.jpeg?q=70",
        "price": 377,
        "original_price": 1499,
        "discount": "74% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "vedapulse",
            "quercetin",
            "500mg",
            "capsules",
            "–",
            "allergy",
            "relief",
            "&",
            "i..."
        ],
        "rating": "4.2",
        "stock_count": 80,
        "in_stock": true,
        "created_at": "2025-07-25T18:33:34.034Z",
        "review_count": 22,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "vedapulse-quercetin-500mg-capsules-allergy-relief-i-69"
    },
    {
        "id": "VSLGPJTYMV3VWNCA",
        "title": "GYNESUTRA Haridra Plus for beautiful glowing skin|Anti ...",
        "image": "https://rukminim2.flixcart.com/image/612/612/xif0q/vitamin-supplement/d/p/r/60-haridra-plus-for-beautiful-glowing-skin-anti-pigmentation-original-imagpn5gy2mrykkx.jpeg?q=70",
        "price": 299,
        "original_price": 999,
        "discount": "70% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "gynesutra",
            "haridra",
            "plus",
            "for",
            "beautiful",
            "glowing",
            "skin|anti",
            "..."
        ],
        "rating": "3.1",
        "stock_count": 77,
        "in_stock": true,
        "created_at": "2025-08-08T16:51:03.240Z",
        "review_count": 425,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "gynesutra-haridra-plus-for-beautiful-glowing-skin-anti-70"
    },
    {
        "id": "VSLGFVTNJMNBRTHZ",
        "title": "NutritJet Magnesium Citrate - 400mg - (120 Vegetarian C...",
        "image": "https://rukminim2.flixcart.com/image/612/612/kmxsakw0/vitamin-supplement/9/b/f/120-nut-mag-400-nutritjet-original-imagfq77kbuzvart.jpeg?q=70",
        "price": 693,
        "original_price": 1199,
        "discount": "42% off",
        "category": "health_and_nutritions",
        "subCategory": "health_and_nutritions",
        "tags": [
            "nutritjet",
            "magnesium",
            "citrate",
            "-",
            "400mg",
            "-",
            "(120",
            "vegetarian",
            "c..."
        ],
        "rating": "4.7",
        "stock_count": 72,
        "in_stock": true,
        "created_at": "2025-09-12T22:56:51.497Z",
        "review_count": 107,
        "size": null,
        "related_products": [],
        "embedding": [],
        "slug": "nutritjet-magnesium-citrate-400mg-120-vegetarian-c-71"
    }
]